logging:
  level:
    org.springframework: INFO

spring:
  main:
    banner-mode: off

token-api:
  enabled: true
  users:
    - user: test1
      password: secret
    - user: test2
      password: secret

management:
  endpoints:
    web:
      exposure:
        include: "health,info,mappings"
  endpoint:
    info:
      enabled: true
    mappings:
      enabled: true
  info:
    git:
      mode: full

